# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'critical_error_form.ui'
#
# Created: Sun Feb 17 00:13:42 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_critical_error_form(object):
    def setupUi(self, critical_error_form):
        critical_error_form.setObjectName(_fromUtf8("critical_error_form"))
        critical_error_form.setWindowModality(QtCore.Qt.ApplicationModal)
        critical_error_form.resize(914, 680)
        self.verticalLayout_3 = QtGui.QVBoxLayout(critical_error_form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.error_message_label = QtGui.QLabel(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_message_label.sizePolicy().hasHeightForWidth())
        self.error_message_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error_message_label.setFont(font)
        self.error_message_label.setLineWidth(1)
        self.error_message_label.setTextFormat(QtCore.Qt.RichText)
        self.error_message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_message_label.setObjectName(_fromUtf8("error_message_label"))
        self.verticalLayout_3.addWidget(self.error_message_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.show_backtrace_button = QtGui.QPushButton(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_backtrace_button.sizePolicy().hasHeightForWidth())
        self.show_backtrace_button.setSizePolicy(sizePolicy)
        self.show_backtrace_button.setObjectName(_fromUtf8("show_backtrace_button"))
        self.horizontalLayout.addWidget(self.show_backtrace_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.back_trace_text_browser = QtGui.QTextEdit(critical_error_form)
        self.back_trace_text_browser.setEnabled(True)
        self.back_trace_text_browser.setMinimumSize(QtCore.QSize(800, 500))
        self.back_trace_text_browser.setDocumentTitle(_fromUtf8(""))
        self.back_trace_text_browser.setReadOnly(True)
        self.back_trace_text_browser.setObjectName(_fromUtf8("back_trace_text_browser"))
        self.verticalLayout_2.addWidget(self.back_trace_text_browser)
        self.checkBox = QtGui.QCheckBox(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setCheckable(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_2.addWidget(self.checkBox)
        self.expert_group_box = QtGui.QGroupBox(critical_error_form)
        self.expert_group_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expert_group_box.sizePolicy().hasHeightForWidth())
        self.expert_group_box.setSizePolicy(sizePolicy)
        self.expert_group_box.setFlat(False)
        self.expert_group_box.setCheckable(False)
        self.expert_group_box.setObjectName(_fromUtf8("expert_group_box"))
        self.formLayout = QtGui.QFormLayout(self.expert_group_box)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.new_issue_button = QtGui.QPushButton(self.expert_group_box)
        self.new_issue_button.setObjectName(_fromUtf8("new_issue_button"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.new_issue_button)
        self.verticalLayout_2.addWidget(self.expert_group_box)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.send_email_button = QtGui.QPushButton(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_email_button.sizePolicy().hasHeightForWidth())
        self.send_email_button.setSizePolicy(sizePolicy)
        self.send_email_button.setObjectName(_fromUtf8("send_email_button"))
        self.verticalLayout.addWidget(self.send_email_button)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.exit_button = QtGui.QPushButton(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.verticalLayout.addWidget(self.exit_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.ok_button = QtGui.QPushButton(critical_error_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_button.sizePolicy().hasHeightForWidth())
        self.ok_button.setSizePolicy(sizePolicy)
        self.ok_button.setObjectName(_fromUtf8("ok_button"))
        self.verticalLayout.addWidget(self.ok_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(critical_error_form)
        QtCore.QObject.connect(self.ok_button, QtCore.SIGNAL(_fromUtf8("clicked()")), critical_error_form.accept)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.expert_group_box.setVisible)
        QtCore.QMetaObject.connectSlotsByName(critical_error_form)
        critical_error_form.setTabOrder(self.exit_button, self.ok_button)
        critical_error_form.setTabOrder(self.ok_button, self.checkBox)

    def retranslateUi(self, critical_error_form):
        critical_error_form.setWindowTitle(QtGui.QApplication.translate("critical_error_form", "Elbrea Critical Error", None, QtGui.QApplication.UnicodeUTF8))
        self.error_message_label.setText(QtGui.QApplication.translate("critical_error_form", "Error Message", None, QtGui.QApplication.UnicodeUTF8))
        self.show_backtrace_button.setText(QtGui.QApplication.translate("critical_error_form", "Show Back Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.back_trace_text_browser.setHtml(QtGui.QApplication.translate("critical_error_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Back Trace</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("critical_error_form", "Expert Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.expert_group_box.setTitle(QtGui.QApplication.translate("critical_error_form", "Expert", None, QtGui.QApplication.UnicodeUTF8))
        self.new_issue_button.setText(QtGui.QApplication.translate("critical_error_form", "New Issue", None, QtGui.QApplication.UnicodeUTF8))
        self.send_email_button.setText(QtGui.QApplication.translate("critical_error_form", "Send Email", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_button.setText(QtGui.QApplication.translate("critical_error_form", "Exit Elbrea", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_button.setText(QtGui.QApplication.translate("critical_error_form", "OK", None, QtGui.QApplication.UnicodeUTF8))

