#! /usr/bin/env python
# -*- python -*-

####################################################################################################
# 
# Elbrea - Electronic Board Reverse Engineering Assistant
# Copyright (C) 2014 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
####################################################################################################

####################################################################################################

import argparse

####################################################################################################

from PrettyPrintGas import PrettyPrintGas

####################################################################################################
#
# Options
#

argument_parser = argparse.ArgumentParser()

argument_parser.add_argument('file_name', metavar='FILE.S',
                             help='File Name')

args = argument_parser.parse_args()

####################################################################################################

input_file = args.file_name
output_file = input_file.replace('.s', '.pp.s')
# output_file = sys.stdout

with open(output_file, 'w') as output:
    pretty_print_gas = PrettyPrintGas(input_file, output)

    # pretty_print_gas.lex()
    pretty_print_gas.pretty_print()

####################################################################################################
#
# End
#
####################################################################################################
