#! /usr/bin/env python
# -*- python -*-

####################################################################################################

import argparse

####################################################################################################

from PrettyPrintGas import PrettyPrintGas

####################################################################################################
#
# Options
#

argument_parser = argparse.ArgumentParser()

argument_parser.add_argument('file_name', metavar='FILE.S',
                             help='File Name')

args = argument_parser.parse_args()

####################################################################################################

input_file = args.file_name
output_file = input_file.replace('.s', '.pp.s')
# output_file = sys.stdout

with open(output_file, 'w') as output:
    pretty_print_gas = PrettyPrintGas(input_file, output)

    # pretty_print_gas.lex()
    pretty_print_gas.pretty_print()

####################################################################################################
#
# End
#
####################################################################################################
